# Site settings
title:          Dapaopao 
description:    "Dapaopao's Blog"
url:            https://wudidapaopao.github.io/wudidapaopao/

# Author
author:
  name:         Dapaopao 
  email:        664920313@qq.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        999
  min_common_tags:  1

# Links to social media
#social:
  #email: inelaah@gmail.com
  #github: https://github.com/inelaah
  #twitter: https://twitter.com
  #linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
